### PR TITLE
Change voting process

### PR DESCRIPTION
**Pull request by shntnu**
It isn't efficient to reach out to the Society at large to vote on positions until we settle on an exact schedule for elections (1/year or 2/year).

### CODE REVIEW

**Comment by shntnu** [comment]
@lopaavol @fheigwer @jccaicedo @gwaygenomics @AnneCarpenter @okraus

Please use 👍 or 👎 to vote on this change for the election process for non-VP positions:

[Old](https://github.com/cytodata/cytods/blob/62655ca6371e8ac75f036d88cd71f943ce12a735/content/leadership.md#other-positions): The Communication Officer send out a list for the Society to vote on. Majority of votes wins; if it’s a tie the Board will vote.	

New: The Communication Officer sends out a list to the Board to vote on. If it’s a tie, the President decides.

Reason: It isn't efficient to reach out to the Society each time there is an open position in the Board. We can go back to doing so once we settle on an exact schedule for elections (1/year or 2/year).

**Comment by AnneCarpenter** [comment]
I like the idea of reaching out to the whole society periodically, if only to remind them that a Board exists and maybe they should consider running in the future. But it should be decided by those who actually have to do more work if we go that route  :)

**Comment by lopaavol** [comment]
It would be good practice to contact the society yearly to let them know that interested ones can apply for a position in the Board. This could be done around the same time that the President changes (or starts the second term). We should also decide when the term changes as so far its been around the time after the yearly meeting. Maybe calendar year would be easier to follow?

**Comment by fheigwer** [comment]
True. For me, the annual meeting was always a good point of orientation. But a welcome email by the new president and some updates on the activities are certainly good. Maybe Lassi can commission a info mail that CytoData takes place this year. Still at recursion but virtual?

--
Florian Heigwer, PhD
Signalling and Functional Genomics /B110
Post-Doc / Boutros Lab

German Cancer Research Center (DKFZ)
Foundation under Public Law
Im Neuenheimer Feld 280
69120 Heidelberg
Germany

f.heigwer@dkfz.de
www.dkfz.de
Management Board: Prof. Dr. med. Michael Baumann, Ursula Weyrich
VAT-ID No.: DE143293537

**Comment by shntnu** [comment]
I am leaving this unchanged, although we may take this (#14) approach in 2020, when board positions are in flux.

**Pull request closed without merging**
