### PR TITLE
Add membership section

### PR DESCRIPTION
**Pull request by lopaavol**
I updated the info regarding CytoData Symposium 2021 and added a new membership section to the website.

### CODE REVIEW

**Comment by wagenrace** [comment]
I tried to make a local build of the site but that did not work. I needed to remove `Markdownify` in ` {{ .Content | markdownify }}` in `themes\hugo-simpledoc-theme\layouts\index.html`

**Comment by fheigwer** [comment]
Well done. Maybe the Membership disclaimer could sound a bit less dry? Maybe simply turn it around and First Say Who we are and what we do and that one can subscribe and Refer to the Legal status below, more as a footnote.

**Comment by lopaavol** [comment]
@wagenrace This is the netlify built deployed version: https://deploy-preview-23--cytods.netlify.app/

**Comment by fheigwer** [comment]
this can be merged I believe?

**Review by fheigwer — COMMENTED** [review]
all good now

**Comment by wagenrace** [comment]
@lopaavol I think this PR can be discarded right?

**Comment by lopaavol** [comment]
Yes. I will check if anything needed for the new site from these modifications.

**Comment by lopaavol** [comment]
The site was changed to multi-page before merging this pull request.

**Pull request closed without merging**
